#pragma once

#include "../definitions/systems/render_system.hpp"
// #include "../definitions/systems/visibility_system.hpp"
// #include "../definitions/systems/minimap_system.hpp"
#include "../definitions/systems/game_loop_system.hpp"
#include "../definitions/systems/geometry_system.hpp"
#include "../definitions/systems/window_system.hpp"
#include "../definitions/systems/input_system.hpp"
#include "../definitions/systems/animation_system.hpp"
#include "../definitions/systems/spawning_system.hpp"
#include "../definitions/systems/scene_system.hpp"
#include "../definitions/systems/texture_system.hpp"
#include "../definitions/systems/gpu_program_system.hpp"
#include "../definitions/systems/easy_drawable_system.hpp"
#include "../definitions/systems/touchscreen_system.hpp"
#include "../definitions/systems/text_system.hpp"
#include "../definitions/systems/level_loader_system.hpp"
#include "../declarations/color_system.hpp"
#include "../declarations/collision_system.hpp"
#include "../declarations/shader_system.hpp"
#include "../declarations/texture_system.hpp"
#include "../declarations/text_system.hpp"
#include "../declarations/input_system.hpp"
#include "../declarations/touchscreen_system.hpp"
#include "../declarations/scene_system.hpp"
#include "../declarations/dynamic_system.hpp"
#include "../declarations/render_system.hpp"
#include "../declarations/animation_system.hpp"
#include "../declarations/imgui_system.hpp"
#include "../declarations/cleanup_system.hpp"
#include "../declarations/periodic_spawner_system.hpp"
#include "../declarations/debug_system.hpp"
#include "../declarations/logger_system.hpp"
#include "../declarations/blinking_system.hpp"
#include "../declarations/deferred_system.hpp"